{{- if .Values.buildkitdToml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
data:
  buildkitd.toml: |
    {{- .Values.buildkitdToml | nindent 4 }}
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIRALyGPTcTTnAo8BR1LXO5aa4wDQYJKoZIhvcNAQELBQAw
    FDESMBAGA1UEAxMJaGFyYm9yLWNhMB4XDTI0MTAxNjIyMzYxNloXDTI1MTAxNjIy
    MzYxNlowFDESMBAGA1UEAxMJaGFyYm9yLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEA6voQWSM7PWtNHxDPcRRFyXOKROqfeG4iCbx8yCjpVG3g6ZP+
    lIMGtTmhdghNFCCtWYubJ0FleajJo+yvcbkDrU0b5kzitdhQCZqNobU1jWqPnHAV
    hlAkQic8xZ6hSqf/HB5j4Z4h1KKxG/8zWx1Yl4CEUPTks89wz+zk87L0G1ufbCZG
    pFhh/v+vn1Ke67sCBiDS7eMTZOBUg5o7Cua4qfkT9ZWgTYZ5Z0rFWu+NCc4lteyz
    NWLVmXbGY4W7WTlTf/pYnFtd97xtKdrQsdHKCRc1TX5ncpMIz2mvOPhBcTjqw6e1
    ZtXkcopU9YQcHxaXJcMt12a8wXBkQXUmxT/SuwIDAQABo2EwXzAOBgNVHQ8BAf8E
    BAMCAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFHDvR4hJmI8Uho7BLkzV2MocBE2TMA0GCSqGSIb3DQEB
    CwUAA4IBAQCOSsCODHgLNxS1t9eu1J8Tr/WO7ympgk4sgiOCSY15S0wXjL5e3vy7
    t78XybcFU5NJXbjVCmIWZBV+IKIEVx+LUDlk9jKhI6TvdBCMrCjLCaQAGspQq0Yi
    j6SbROSuooksSjoMYMaHBFEET1jckWccitPGpmDWYUmglgAZa5DIR7FaUknktAJa
    W7q+47tdlkbzpnUAy5lEAuXfHpWHya1XDHYP1e/o4stslgy9xUdN9SM+UJzOVu9b
    YIUxoPqCrtb7NV2dKjbZ18mayEZ9VAKycVN7RoGkyAds7ylatUeqka8ct1ez8O72
    spi4lrbiPySEh5O8rE7GjTzSYjlx5eS7
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDNTCCAh2gAwIBAgIRAPYqHzwU3rkh7wH0dLhEbEYwDQYJKoZIhvcNAQELBQAw
    FDESMBAGA1UEAxMJaGFyYm9yLWNhMB4XDTI0MTAxNjIyMzYxNloXDTI1MTAxNjIy
    MzYxNlowGjEYMBYGA1UEAxMPaGFyYm9yLmludGVybmFsMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAwd/6xMl5yH0d0csLFk0bDPifg+A1B4nPKkNw3t9h
    vzC2CpLwH4TsndKBUNo7il4W7K1HTx4CrJ98mZ3yUKndIN4q8Yf41rf0x8DGN5mZ
    uVsI8/B7tp1B9FT5OQ8v89kUi4t+dfhq+29GqnnAO46QSnnwG4h2CSx6/iztbwT6
    b3HLnPfH22R/wjSWv5mzPmBf3gf4U3nypUDpfNwLKbwZr3tcW+2hZY8MpYF1n8Z2
    JPWBqCteW2axscTY4/iYm9QQJdYqVZDVDdgOs4NFmd1/kgeL0O3l0Ksd0Wbz94v2
    5OlTXsrYkcrrvXtcRVYIDQ1RwHMSfOVwsMAoU/PlR5UpXQIDAQABo3wwejAOBgNV
    HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
    EwEB/wQCMAAwHwYDVR0jBBgwFoAUcO9HiEmYjxSGjsEuTNXYyhwETZMwGgYDVR0R
    BBMwEYIPaGFyYm9yLmludGVybmFsMA0GCSqGSIb3DQEBCwUAA4IBAQCdyNGUYB7g
    ppMXy3KQiaohLIjOkttF4b6oHoT7yaHDOlaiogmy1Na2sGAHpJlH2udGBjVHHu25
    Hr/DDGKBbZT8K0xawj2RW2ON3+2ggLYbxndDIbtbGc05+Rj5fU0RloNZEoG+F2fD
    wFOf44CdvgkQPY4VAa0k1ht5gJbr2m8voN8zHue/PuqsX091l5GrgG9g2G6zOBI5
    X/IxfFY7asJAonheOlTI2q83rgIeef7cOLcAqy+7Nx8P2fnWYMuCVknrLGZSV2nH
    9jCG+WlLUCPbPrCQddu4EZJRVm9lmytjeUHuBGIWEMrWDA9sFzrsN9DutXM5v0KT
    NWc7/v9M2ZBo
    -----END CERTIFICATE-----

{{- end }}
