apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildkit.fullname" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "buildkit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.rootless .Values.podAnnotations }}
      annotations:
        {{- if .Values.rootless }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: unconfined
        {{- end }}
        {{- with .Values.podAnnotations -}}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "buildkit.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: merge-ca-certificates
          image: docker.io/kalaksi/ca-certificates
          volumeMounts:
            - name: new-certs
              mountPath: /etc/ssl/certs
          env:
            - name: CA_CERT_0: 
              value: |
                -----BEGIN CERTIFICATE-----
                MIIDFDCCAfygAwIBAgIRALyGPTcTTnAo8BR1LXO5aa4wDQYJKoZIhvcNAQELBQAw
                FDESMBAGA1UEAxMJaGFyYm9yLWNhMB4XDTI0MTAxNjIyMzYxNloXDTI1MTAxNjIy
                MzYxNlowFDESMBAGA1UEAxMJaGFyYm9yLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOC
                AQ8AMIIBCgKCAQEA6voQWSM7PWtNHxDPcRRFyXOKROqfeG4iCbx8yCjpVG3g6ZP+
                lIMGtTmhdghNFCCtWYubJ0FleajJo+yvcbkDrU0b5kzitdhQCZqNobU1jWqPnHAV
                hlAkQic8xZ6hSqf/HB5j4Z4h1KKxG/8zWx1Yl4CEUPTks89wz+zk87L0G1ufbCZG
                pFhh/v+vn1Ke67sCBiDS7eMTZOBUg5o7Cua4qfkT9ZWgTYZ5Z0rFWu+NCc4lteyz
                NWLVmXbGY4W7WTlTf/pYnFtd97xtKdrQsdHKCRc1TX5ncpMIz2mvOPhBcTjqw6e1
                ZtXkcopU9YQcHxaXJcMt12a8wXBkQXUmxT/SuwIDAQABo2EwXzAOBgNVHQ8BAf8E
                BAMCAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQF
                MAMBAf8wHQYDVR0OBBYEFHDvR4hJmI8Uho7BLkzV2MocBE2TMA0GCSqGSIb3DQEB
                CwUAA4IBAQCOSsCODHgLNxS1t9eu1J8Tr/WO7ympgk4sgiOCSY15S0wXjL5e3vy7
                t78XybcFU5NJXbjVCmIWZBV+IKIEVx+LUDlk9jKhI6TvdBCMrCjLCaQAGspQq0Yi
                j6SbROSuooksSjoMYMaHBFEET1jckWccitPGpmDWYUmglgAZa5DIR7FaUknktAJa
                W7q+47tdlkbzpnUAy5lEAuXfHpWHya1XDHYP1e/o4stslgy9xUdN9SM+UJzOVu9b
                YIUxoPqCrtb7NV2dKjbZ18mayEZ9VAKycVN7RoGkyAds7ylatUeqka8ct1ez8O72
                spi4lrbiPySEh5O8rE7GjTzSYjlx5eS7
                -----END CERTIFICATE-----
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ include "buildkit.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.rootless .Values.tls.enabled .Values.buildkitdToml }}
          volumeMounts:
          {{- if .Values.buildkitdToml }}
            - name: config
              mountPath: {{ if .Values.rootless }}/home/user/.config/buildkit{{ else }}/etc/buildkit{{ end }}
            - name: new-certs
              mountPath: /etc/ssl/certs
          {{- end }}
          {{- if .Values.tls.enabled }}
            - name: certs
              readOnly: true
              mountPath: /certs
          {{- end }}
          {{- if .Values.rootless }}
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
          {{- end }}
          {{- end }}
          args:
            - --addr
            - unix:///run/{{ .Values.rootless | ternary "user/1000" ""}}/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
          {{- if .Values.rootless }}
            - --oci-worker-no-process-sandbox
          {{- end }}
          {{- if .Values.tls.enabled }}
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
          {{- end }}
          {{- if .Values.debugLog }}
            - --debug
          {{- end }}
          ports:
            - name: tcp
              containerPort: 1234
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - buildctl
              - debug
              - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
          {{- if .Values.rootless }}
            seccompProfile: # Needs Kubernetes >= 1.19
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          {{- else }}
            privileged: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if or .Values.rootless .Values.tls.enabled .Values.buildkitdToml }}
      volumes:
      - name: new-certs
        emptyDir: {}
      {{- if .Values.buildkitdToml }}
      - name: config
        configMap:
          name: buildkitd-config
      {{- end }}
      {{- if .Values.rootless }}
      - name: buildkitd
        emptyDir: {}
      {{- end }}
      {{- if .Values.tls.enabled }}
      - name: certs
        secret:
          secretName: {{ include "buildkit.fullname" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
